from datetime import datetime
from pathlib import Path


def write_markdown(target_path: str, explanation: str, analysis_data: dict) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_name = "RECON_REPORT.md"

    files = analysis_data.get("files", [])
    signals = analysis_data.get("signals", [])

    # FIX: Extract the 'path' key from the file dictionary
    ext_map = {}
    for f_obj in files:
        # Check if it's a dict (with a 'path' key) or just a string
        f_path = f_obj.get('path', '') if isinstance(f_obj, dict) else str(f_obj)

        if f_path:
            ext = Path(f_path).suffix or "no-ext"
            ext_map[ext] = ext_map.get(ext, 0) + 1

    tech_stack = ", ".join([f"{k} ({v})" for k, v in ext_map.items()])

    header = f"""# 🔍 CodeRecon Audit Report
> **Target:** `{target_path}`
> **Generated:** {timestamp}

## 📊 Technical Snapshot
| Metric | Value |
| :--- | :--- |
| **Total Files** | {len(files)} |
| **Tech Stack** | {tech_stack} |
| **Risk Signals** | {len(signals)} |

---

{explanation}

---
*Generated by CodeRecon v1.0 - Local & Private Intelligence*
"""

    with open(report_name, "w", encoding="utf-8") as f:
        f.write(header)

    return report_name